name: My first Github Action

on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repository code
      - uses: actions/setup-node@v2 # Setup Node.js
        with:
          node-version: '18'
      - name: Install node_modules
        run: yarn install # Install dependencies
      - name: Install Vercel CLI
        run: npm install -g vercel # Install Vercel CLI globally
      - name: Build the project
        run: yarn build
      - name: Sets the Vercel environment
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{"projectId":"prj_Fvxakj6xnmL7MbHfsPMhUKGXtEog","orgId":"team_N9R141dNqVCtAdVEU52DtAWx"}' > project.json
      - name: Deploying the project
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes # Use secure token from secrets
      - name: Setup finish
        run: echo "Setup finished, hurrah!"